//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.Plugins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Avalonia.Plugins.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All versions.
        /// </summary>
        public static string InstalledPluginsView_AllVersions {
            get {
                return ResourceManager.GetString("InstalledPluginsView_AllVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string InstalledPluginsView_CancelUninstall {
            get {
                return ResourceManager.GetString("InstalledPluginsView_CancelUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading error.
        /// </summary>
        public static string InstalledPluginsView_LoadingError {
            get {
                return ResourceManager.GetString("InstalledPluginsView_LoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string InstalledPluginsView_Search {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select plugin.
        /// </summary>
        public static string InstalledPluginsView_SelectedPluginIsNull {
            get {
                return ResourceManager.GetString("InstalledPluginsView_SelectedPluginIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string InstalledPluginsView_Tab_AdditionalInfo {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: .
        /// </summary>
        public static string InstalledPluginsView_Tab_AdditionalInfo_Author {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies: .
        /// </summary>
        public static string InstalledPluginsView_Tab_AdditionalInfo_Dependencies {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads: .
        /// </summary>
        public static string InstalledPluginsView_Tab_AdditionalInfo_DownloadCount {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo_DownloadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags: .
        /// </summary>
        public static string InstalledPluginsView_Tab_AdditionalInfo_Tags {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string InstalledPluginsView_Tab_Description {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string InstalledPluginsView_Uninstall {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled.
        /// </summary>
        public static string InstalledPluginsView_Uninstalled {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin has been marked for deletion. It will be removed on the next application load..
        /// </summary>
        public static string InstalledPluginsView_UninstalledMessage {
            get {
                return ResourceManager.GetString("InstalledPluginsView_UninstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalled.
        /// </summary>
        public static string InstalledPluginsView_UninstalledMessageTitle {
            get {
                return ResourceManager.GetString("InstalledPluginsView_UninstalledMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Installed Plagins.
        /// </summary>
        public static string OpenInstalledPluginsCommand_Action_Description {
            get {
                return ResourceManager.GetString("OpenInstalledPluginsCommand_Action_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Plugins.
        /// </summary>
        public static string OpenInstalledPluginsCommand_Action_Title {
            get {
                return ResourceManager.GetString("OpenInstalledPluginsCommand_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string PluginInstallerViewModel_InstallDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PluginInstallerViewModel_InstallDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Installer.
        /// </summary>
        public static string PluginInstallerViewModel_InstallDialog_Title {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin installed successfully.
        /// </summary>
        public static string PluginInstallerViewModel_InstallPluginAsync_Success {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallPluginAsync_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PluginsMarketView_Cancel {
            get {
                return ResourceManager.GetString("PluginsMarketView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin is verified by developers.
        /// </summary>
        public static string PluginsMarketView_InfoBar_IsVerified_Message {
            get {
                return ResourceManager.GetString("PluginsMarketView_InfoBar_IsVerified_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string PluginsMarketView_Install {
            get {
                return ResourceManager.GetString("PluginsMarketView_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select plugin.
        /// </summary>
        public static string PluginsMarketView_SelectedPluginIsNull {
            get {
                return ResourceManager.GetString("PluginsMarketView_SelectedPluginIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only verified.
        /// </summary>
        public static string PluginsMarketView_ToggleSwitch_OnlyVerified {
            get {
                return ResourceManager.GetString("PluginsMarketView_ToggleSwitch_OnlyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string PluginsSourcesViewModel_AddAction_Label {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_AddAction_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string PluginsSourcesViewModel_AddImpl_Add {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_AddImpl_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PluginsSourcesViewModel_AddImpl_Cancel {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_AddImpl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new plugin source.
        /// </summary>
        public static string PluginsSourcesViewModel_AddImpl_Title {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_AddImpl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PluginsSourcesViewModel_EditImpl_Save {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_EditImpl_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit plugin source.
        /// </summary>
        public static string PluginsSourcesViewModel_EditImpl_Title {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_EditImpl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins Sources.
        /// </summary>
        public static string PluginsSourcesViewModel_Name {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to remove plugin server.
        /// </summary>
        public static string PluginsSourcesViewModel_PluginsSourcesViewModel_ErrorToRemove {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_PluginsSourcesViewModel_ErrorToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to update plugin server list.
        /// </summary>
        public static string PluginsSourcesViewModel_PluginsSourcesViewModel_ErrorToUpdate {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_PluginsSourcesViewModel_ErrorToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SourcesView_Name {
            get {
                return ResourceManager.GetString("SourcesView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string SourcesView_Password {
            get {
                return ResourceManager.GetString("SourcesView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Address.
        /// </summary>
        public static string SourcesView_URL {
            get {
                return ResourceManager.GetString("SourcesView_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SourcesView_Username {
            get {
                return ResourceManager.GetString("SourcesView_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string SourceViewModel_NameValidation_NameIsRequired {
            get {
                return ResourceManager.GetString("SourceViewModel_NameValidation_NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URI is required.
        /// </summary>
        public static string SourceViewModel_SourceUriValidation_SourceUriIsRequired {
            get {
                return ResourceManager.GetString("SourceViewModel_SourceUriValidation_SourceUriIsRequired", resourceCulture);
            }
        }
    }
}
