//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.Plugins {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Avalonia.Plugins.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string InstalledPluginsView_Search {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Search", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Uninstalled {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Uninstalled", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_LoadingError {
            get {
                return ResourceManager.GetString("InstalledPluginsView_LoadingError", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Uninstall {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Uninstall", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_UninstalledMessageTitle {
            get {
                return ResourceManager.GetString("InstalledPluginsView_UninstalledMessageTitle", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_UninstalledMessage {
            get {
                return ResourceManager.GetString("InstalledPluginsView_UninstalledMessage", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_CancelUninstall {
            get {
                return ResourceManager.GetString("InstalledPluginsView_CancelUninstall", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Tab_Description {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_Description", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Tab_AdditionalInfo {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo", resourceCulture);
            }
        }
        
        public static string PluginsMarketView_ToggleSwitch_OnlyVerified {
            get {
                return ResourceManager.GetString("PluginsMarketView_ToggleSwitch_OnlyVerified", resourceCulture);
            }
        }
        
        public static string PluginsMarketView_InfoBar_IsVerified_Message {
            get {
                return ResourceManager.GetString("PluginsMarketView_InfoBar_IsVerified_Message", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_SelectedPluginIsNull {
            get {
                return ResourceManager.GetString("InstalledPluginsView_SelectedPluginIsNull", resourceCulture);
            }
        }
        
        public static string PluginInstallerViewModel_InstallDialog_Title {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallDialog_Title", resourceCulture);
            }
        }
        
        public static string PluginInstallerViewModel_InstallPluginAsync_Success {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallPluginAsync_Success", resourceCulture);
            }
        }
        
        public static string PluginsMarketView_Install {
            get {
                return ResourceManager.GetString("PluginsMarketView_Install", resourceCulture);
            }
        }
        
        public static string PluginsMarketView_SelectedPluginIsNull {
            get {
                return ResourceManager.GetString("PluginsMarketView_SelectedPluginIsNull", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Tab_AdditionalInfo_Dependencies {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo_Dependencies", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_AllVersions {
            get {
                return ResourceManager.GetString("InstalledPluginsView_AllVersions", resourceCulture);
            }
        }
        
        public static string PluginsMarketView_Cancel {
            get {
                return ResourceManager.GetString("PluginsMarketView_Cancel", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Tab_AdditionalInfo_Author {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo_Author", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Tab_AdditionalInfo_DownloadCount {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo_DownloadCount", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Tab_AdditionalInfo_Tags {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo_Tags", resourceCulture);
            }
        }
        
        public static string SourceViewModel_NameValidation_NameIsRequired {
            get {
                return ResourceManager.GetString("SourceViewModel_NameValidation_NameIsRequired", resourceCulture);
            }
        }
        
        public static string SourceViewModel_SourceUriValidation_SourceUriIsRequired {
            get {
                return ResourceManager.GetString("SourceViewModel_SourceUriValidation_SourceUriIsRequired", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_PluginsSourcesViewModel_ErrorToUpdate {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_PluginsSourcesViewModel_ErrorToUpdate", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_PluginsSourcesViewModel_ErrorToRemove {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_PluginsSourcesViewModel_ErrorToRemove", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_AddImpl_Title {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_AddImpl_Title", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_AddImpl_Add {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_AddImpl_Add", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_AddImpl_Cancel {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_AddImpl_Cancel", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_EditImpl_Title {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_EditImpl_Title", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_EditImpl_Save {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_EditImpl_Save", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_AddAction_Label {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_AddAction_Label", resourceCulture);
            }
        }
        
        public static string SourcesView_Name {
            get {
                return ResourceManager.GetString("SourcesView_Name", resourceCulture);
            }
        }
        
        public static string SourcesView_URL {
            get {
                return ResourceManager.GetString("SourcesView_URL", resourceCulture);
            }
        }
        
        public static string SourcesView_Username {
            get {
                return ResourceManager.GetString("SourcesView_Username", resourceCulture);
            }
        }
        
        public static string SourcesView_Password {
            get {
                return ResourceManager.GetString("SourcesView_Password", resourceCulture);
            }
        }
        
        public static string PluginInstallerViewModel_InstallDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        public static string PluginInstallerViewModel_InstallDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string OpenInstalledPluginsCommand_Action_Title {
            get {
                return ResourceManager.GetString("OpenInstalledPluginsCommand_Action_Title", resourceCulture);
            }
        }
        
        public static string OpenInstalledPluginsCommand_Action_Description {
            get {
                return ResourceManager.GetString("OpenInstalledPluginsCommand_Action_Description", resourceCulture);
            }
        }
    }
}
