//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.LogViewer {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Avalonia.LogViewer.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LogViewerView_Button_Filters {
            get {
                return ResourceManager.GetString("LogViewerView_Button_Filters", resourceCulture);
            }
        }
        
        public static string LogViewerView_SearchText_Watermark {
            get {
                return ResourceManager.GetString("LogViewerView_SearchText_Watermark", resourceCulture);
            }
        }
        
        public static string LogViewerView_TextBlock_By_Title {
            get {
                return ResourceManager.GetString("LogViewerView_TextBlock_By_Title", resourceCulture);
            }
        }
        
        public static string LogViewerView_TextBlock_TotalItemsCount {
            get {
                return ResourceManager.GetString("LogViewerView_TextBlock_TotalItemsCount", resourceCulture);
            }
        }
        
        public static string LogViewerView_TextBlock_FilteredItemsCount {
            get {
                return ResourceManager.GetString("LogViewerView_TextBlock_FilteredItemsCount", resourceCulture);
            }
        }
        
        public static string LogViewerView_TextBlock_PageItemsCount {
            get {
                return ResourceManager.GetString("LogViewerView_TextBlock_PageItemsCount", resourceCulture);
            }
        }
        
        public static string LogViewerView_Apply_Filters_Button {
            get {
                return ResourceManager.GetString("LogViewerView_Apply_Filters_Button", resourceCulture);
            }
        }
        
        public static string LogViewView_Levels_Text {
            get {
                return ResourceManager.GetString("LogViewView_Levels_Text", resourceCulture);
            }
        }
        
        public static string LogViewView_Sources_Text {
            get {
                return ResourceManager.GetString("LogViewView_Sources_Text", resourceCulture);
            }
        }
        
        public static string LogViewer_Title {
            get {
                return ResourceManager.GetString("LogViewer_Title", resourceCulture);
            }
        }
        
        public static string LogViewerViewModel_ClearDialog_Title {
            get {
                return ResourceManager.GetString("LogViewerViewModel_ClearDialog_Title", resourceCulture);
            }
        }
        
        public static string LogViewerViewModel_ClearDialog_Content {
            get {
                return ResourceManager.GetString("LogViewerViewModel_ClearDialog_Content", resourceCulture);
            }
        }
        
        public static string LogViewerViewModel_ClearDialog_CloseButton {
            get {
                return ResourceManager.GetString("LogViewerViewModel_ClearDialog_CloseButton", resourceCulture);
            }
        }
        
        public static string LogViewerViewModel_ClearDialog_PrimaryButton {
            get {
                return ResourceManager.GetString("LogViewerViewModel_ClearDialog_PrimaryButton", resourceCulture);
            }
        }
        
        public static string LogViewerView_Categories {
            get {
                return ResourceManager.GetString("LogViewerView_Categories", resourceCulture);
            }
        }
        
        public static string LogViewerView_Levels {
            get {
                return ResourceManager.GetString("LogViewerView_Levels", resourceCulture);
            }
        }
        
        public static string LogViewerView_Threads {
            get {
                return ResourceManager.GetString("LogViewerView_Threads", resourceCulture);
            }
        }
    }
}
