//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Avalonia.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ChangeLanguageCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeLanguageCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ChangeLanguageCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeLanguageCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string SettingsAppearanceView_AppLanguage_Title {
            get {
                return ResourceManager.GetString("SettingsAppearanceView_AppLanguage_Title", resourceCulture);
            }
        }
        
        public static string ThemeService_Dark {
            get {
                return ResourceManager.GetString("ThemeService_Dark", resourceCulture);
            }
        }
        
        public static string ThemeService_Light {
            get {
                return ResourceManager.GetString("ThemeService_Light", resourceCulture);
            }
        }
        
        public static string ThemeService_System {
            get {
                return ResourceManager.GetString("ThemeService_System", resourceCulture);
            }
        }
        
        public static string SettingsAppearanceView_AppTheme_Title {
            get {
                return ResourceManager.GetString("SettingsAppearanceView_AppTheme_Title", resourceCulture);
            }
        }
        
        public static string SettingsAppearanceView_HubHeader_CommonSettings {
            get {
                return ResourceManager.GetString("SettingsAppearanceView_HubHeader_CommonSettings", resourceCulture);
            }
        }
        
        public static string SettingsUnitsView_Header_Name {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Name", resourceCulture);
            }
        }
        
        public static string SettingsUnitsView_Header_Description {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Description", resourceCulture);
            }
        }
        
        public static string SettingsUnitsView_Header_Selected {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Selected", resourceCulture);
            }
        }
        
        public static string SettingsUnitsView_Header_Default {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Default", resourceCulture);
            }
        }
        
        public static string Distance_Name {
            get {
                return ResourceManager.GetString("Distance_Name", resourceCulture);
            }
        }
        
        public static string Distance_Description {
            get {
                return ResourceManager.GetString("Distance_Description", resourceCulture);
            }
        }
        
        public static string OpenDebugCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenDebugCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenDebugCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenDebugCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string UndoCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("UndoCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string RedoCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("RedoCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string UndoCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("UndoCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string RedoCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("RedoCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string HomePageViewModel_Title {
            get {
                return ResourceManager.GetString("HomePageViewModel_Title", resourceCulture);
            }
        }
        
        public static string SettingsPageViewModel_Title {
            get {
                return ResourceManager.GetString("SettingsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string SettingsAppearanceViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsAppearanceViewModel_Name", resourceCulture);
            }
        }
        
        public static string SettingsUnitsViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsUnitsViewModel_Name", resourceCulture);
            }
        }
        
        public static string SettingsHotKeysListViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsHotKeysListViewModel_Name", resourceCulture);
            }
        }
        
        public static string NauticalMile_UnitItem_Name {
            get {
                return ResourceManager.GetString("NauticalMile_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string NauticalMile_Distance_Description {
            get {
                return ResourceManager.GetString("NauticalMile_Distance_Description", resourceCulture);
            }
        }
        
        public static string ShellView_WindowControlButton_Close {
            get {
                return ResourceManager.GetString("ShellView_WindowControlButton_Close", resourceCulture);
            }
        }
        
        public static string ShellView_WindowControlButton_Maximize {
            get {
                return ResourceManager.GetString("ShellView_WindowControlButton_Maximize", resourceCulture);
            }
        }
        
        public static string ShellView_WindowControlButton_Minimize {
            get {
                return ResourceManager.GetString("ShellView_WindowControlButton_Minimize", resourceCulture);
            }
        }
        
        public static string ShellView_WindowControlButton_Collapse {
            get {
                return ResourceManager.GetString("ShellView_WindowControlButton_Collapse", resourceCulture);
            }
        }
        
        public static string ShellView_Toolbar_File {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_File", resourceCulture);
            }
        }
        
        public static string ShellView_Toolbar_Edit {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_Edit", resourceCulture);
            }
        }
        
        public static string ShellView_Toolbar_View {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_View", resourceCulture);
            }
        }
        
        public static string ShellView_Toolbar_Help {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_Help", resourceCulture);
            }
        }
        
        public static string ChangeCurrentUnitItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeCurrentUnitItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ChangeCurrentUnitItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeCurrentUnitItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string Altitude_Name {
            get {
                return ResourceManager.GetString("Altitude_Name", resourceCulture);
            }
        }
        
        public static string Altitude_Description {
            get {
                return ResourceManager.GetString("Altitude_Description", resourceCulture);
            }
        }
        
        public static string Meter_UnitItem_Name {
            get {
                return ResourceManager.GetString("Meter_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Meter_Altitude_Description {
            get {
                return ResourceManager.GetString("Meter_Altitude_Description", resourceCulture);
            }
        }
        
        public static string Meter_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Meter_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Feet_UnitItem_Name {
            get {
                return ResourceManager.GetString("Feet_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Feet_Altitude_Description {
            get {
                return ResourceManager.GetString("Feet_Altitude_Description", resourceCulture);
            }
        }
        
        public static string Feet_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Feet_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string AmplitudeModulation_Name {
            get {
                return ResourceManager.GetString("AmplitudeModulation_Name", resourceCulture);
            }
        }
        
        public static string AmplitudeModulation_Description {
            get {
                return ResourceManager.GetString("AmplitudeModulation_Description", resourceCulture);
            }
        }
        
        public static string InParts_AmplitudeModulation_Description {
            get {
                return ResourceManager.GetString("InParts_AmplitudeModulation_Description", resourceCulture);
            }
        }
        
        public static string Percent_AmplitudeModulation_Description {
            get {
                return ResourceManager.GetString("Percent_AmplitudeModulation_Description", resourceCulture);
            }
        }
        
        public static string Bearing_Name {
            get {
                return ResourceManager.GetString("Bearing_Name", resourceCulture);
            }
        }
        
        public static string Bearing_Description {
            get {
                return ResourceManager.GetString("Bearing_Description", resourceCulture);
            }
        }
        
        public static string Degree_UnitItem_Name {
            get {
                return ResourceManager.GetString("Degree_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Degree_Bearing_Description {
            get {
                return ResourceManager.GetString("Degree_Bearing_Description", resourceCulture);
            }
        }
        
        public static string DM_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("DM_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string DM_Bearing_Description {
            get {
                return ResourceManager.GetString("DM_Bearing_Description", resourceCulture);
            }
        }
        
        public static string DM_UnitItem_Name {
            get {
                return ResourceManager.GetString("DM_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string DdmGp_Name {
            get {
                return ResourceManager.GetString("DdmGp_Name", resourceCulture);
            }
        }
        
        public static string DdmGp_Description {
            get {
                return ResourceManager.GetString("DdmGp_Description", resourceCulture);
            }
        }
        
        public static string InParts_UnitItem_Name {
            get {
                return ResourceManager.GetString("InParts_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string InParts_DdmGp_Description {
            get {
                return ResourceManager.GetString("InParts_DdmGp_Description", resourceCulture);
            }
        }
        
        public static string Percent_UnitItem_Name {
            get {
                return ResourceManager.GetString("Percent_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Percent_DdmGp_Description {
            get {
                return ResourceManager.GetString("Percent_DdmGp_Description", resourceCulture);
            }
        }
        
        public static string Ddm_µA_Symbol {
            get {
                return ResourceManager.GetString("Ddm_µA_Symbol", resourceCulture);
            }
        }
        
        public static string MicroAmp_UnitItem_Name {
            get {
                return ResourceManager.GetString("MicroAmp_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string MicroAmp_DdmGp_Description {
            get {
                return ResourceManager.GetString("MicroAmp_DdmGp_Description", resourceCulture);
            }
        }
        
        public static string MicroAmpRu_UnitItem_Name {
            get {
                return ResourceManager.GetString("MicroAmpRu_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string MicroAmpRu_DdmGp_Description {
            get {
                return ResourceManager.GetString("MicroAmpRu_DdmGp_Description", resourceCulture);
            }
        }
        
        public static string DdmLlz_Name {
            get {
                return ResourceManager.GetString("DdmLlz_Name", resourceCulture);
            }
        }
        
        public static string DdmLlz_Description {
            get {
                return ResourceManager.GetString("DdmLlz_Description", resourceCulture);
            }
        }
        
        public static string InParts_DdmLlz_Description {
            get {
                return ResourceManager.GetString("InParts_DdmLlz_Description", resourceCulture);
            }
        }
        
        public static string Percent_DdmLlz_Description {
            get {
                return ResourceManager.GetString("Percent_DdmLlz_Description", resourceCulture);
            }
        }
        
        public static string MicroAmp_DdmLlz_Description {
            get {
                return ResourceManager.GetString("MicroAmp_DdmLlz_Description", resourceCulture);
            }
        }
        
        public static string MicroAmpRu_DdmLlz_Description {
            get {
                return ResourceManager.GetString("MicroAmpRu_DdmLlz_Description", resourceCulture);
            }
        }
        
        public static string Angle_Description {
            get {
                return ResourceManager.GetString("Angle_Description", resourceCulture);
            }
        }
        
        public static string Degree_Angle_Description {
            get {
                return ResourceManager.GetString("Degree_Angle_Description", resourceCulture);
            }
        }
        
        public static string Angle_Name {
            get {
                return ResourceManager.GetString("Angle_Name", resourceCulture);
            }
        }
        
        public static string Degree_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Degree_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Ms_UnitItem_Name {
            get {
                return ResourceManager.GetString("Ms_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Ms_Angle_Description {
            get {
                return ResourceManager.GetString("Ms_Angle_Description", resourceCulture);
            }
        }
        
        public static string Ms_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Ms_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Dms_UnitItem_Name {
            get {
                return ResourceManager.GetString("Dms_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Dms_Angle_Description {
            get {
                return ResourceManager.GetString("Dms_Angle_Description", resourceCulture);
            }
        }
        
        public static string Dms_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Dms_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string FieldStrength_Name {
            get {
                return ResourceManager.GetString("FieldStrength_Name", resourceCulture);
            }
        }
        
        public static string FieldStrength_Description {
            get {
                return ResourceManager.GetString("FieldStrength_Description", resourceCulture);
            }
        }
        
        public static string MicroVoltsPerMeter_UnitItem_Name {
            get {
                return ResourceManager.GetString("MicroVoltsPerMeter_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string MicroVoltsPerMeter_FieldStrength_Description {
            get {
                return ResourceManager.GetString("MicroVoltsPerMeter_FieldStrength_Description", resourceCulture);
            }
        }
        
        public static string FieldStrength_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("FieldStrength_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Power_Name {
            get {
                return ResourceManager.GetString("Power_Name", resourceCulture);
            }
        }
        
        public static string Power_Description {
            get {
                return ResourceManager.GetString("Power_Description", resourceCulture);
            }
        }
        
        public static string Dbm_UnitItem_Name {
            get {
                return ResourceManager.GetString("Dbm_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Dbm_Power_Description {
            get {
                return ResourceManager.GetString("Dbm_Power_Description", resourceCulture);
            }
        }
        
        public static string Dbm_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Dbm_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Frequency_Name {
            get {
                return ResourceManager.GetString("Frequency_Name", resourceCulture);
            }
        }
        
        public static string Frequency_Description {
            get {
                return ResourceManager.GetString("Frequency_Description", resourceCulture);
            }
        }
        
        public static string Hertz_UnitItem_Name {
            get {
                return ResourceManager.GetString("Hertz_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Hertz_Frequency_Description {
            get {
                return ResourceManager.GetString("Hertz_Frequency_Description", resourceCulture);
            }
        }
        
        public static string Hertz_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Hertz_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Gigahertz_UnitItem_Name {
            get {
                return ResourceManager.GetString("Gigahertz_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Gigahertz_Frequency_Description {
            get {
                return ResourceManager.GetString("Gigahertz_Frequency_Description", resourceCulture);
            }
        }
        
        public static string Gigahertz_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Gigahertz_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Kilohertz_UnitItem_Name {
            get {
                return ResourceManager.GetString("Kilohertz_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Kilohertz_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Kilohertz_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Kilohertz_Frequency_Description {
            get {
                return ResourceManager.GetString("Kilohertz_Frequency_Description", resourceCulture);
            }
        }
        
        public static string Megahertz_UnitItem_Name {
            get {
                return ResourceManager.GetString("Megahertz_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Megahertz_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Megahertz_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Megahertz_Frequency_Description {
            get {
                return ResourceManager.GetString("Megahertz_Frequency_Description", resourceCulture);
            }
        }
        
        public static string Latitude_Name {
            get {
                return ResourceManager.GetString("Latitude_Name", resourceCulture);
            }
        }
        
        public static string Latitude_Description {
            get {
                return ResourceManager.GetString("Latitude_Description", resourceCulture);
            }
        }
        
        public static string Degree_Latitude_Description {
            get {
                return ResourceManager.GetString("Degree_Latitude_Description", resourceCulture);
            }
        }
        
        public static string Dms_Latitude_Description {
            get {
                return ResourceManager.GetString("Dms_Latitude_Description", resourceCulture);
            }
        }
        
        public static string Longitude_Name {
            get {
                return ResourceManager.GetString("Longitude_Name", resourceCulture);
            }
        }
        
        public static string Longitude_Description {
            get {
                return ResourceManager.GetString("Longitude_Description", resourceCulture);
            }
        }
        
        public static string Degree_Longitude_Description {
            get {
                return ResourceManager.GetString("Degree_Longitude_Description", resourceCulture);
            }
        }
        
        public static string Dms_Longitude_Description {
            get {
                return ResourceManager.GetString("Dms_Longitude_Description", resourceCulture);
            }
        }
        
        public static string Phase_Name {
            get {
                return ResourceManager.GetString("Phase_Name", resourceCulture);
            }
        }
        
        public static string Phase_Description {
            get {
                return ResourceManager.GetString("Phase_Description", resourceCulture);
            }
        }
        
        public static string Degree_Phase_Description {
            get {
                return ResourceManager.GetString("Degree_Phase_Description", resourceCulture);
            }
        }
        
        public static string Radian_UnitItem_Name {
            get {
                return ResourceManager.GetString("Radian_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Radian_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Radian_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Radian_Phase_Description {
            get {
                return ResourceManager.GetString("Radian_Phase_Description", resourceCulture);
            }
        }
        
        public static string Sdm_Name {
            get {
                return ResourceManager.GetString("Sdm_Name", resourceCulture);
            }
        }
        
        public static string Sdm_Description {
            get {
                return ResourceManager.GetString("Sdm_Description", resourceCulture);
            }
        }
        
        public static string Percent_Sdm_Description {
            get {
                return ResourceManager.GetString("Percent_Sdm_Description", resourceCulture);
            }
        }
        
        public static string Temperature_Name {
            get {
                return ResourceManager.GetString("Temperature_Name", resourceCulture);
            }
        }
        
        public static string Temperature_Description {
            get {
                return ResourceManager.GetString("Temperature_Description", resourceCulture);
            }
        }
        
        public static string Kelvin_UnitItem_Name {
            get {
                return ResourceManager.GetString("Kelvin_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Kelvin_Temperature_Description {
            get {
                return ResourceManager.GetString("Kelvin_Temperature_Description", resourceCulture);
            }
        }
        
        public static string Celsius_UnitItem_Name {
            get {
                return ResourceManager.GetString("Celsius_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Celsius_Temperature_Description {
            get {
                return ResourceManager.GetString("Celsius_Temperature_Description", resourceCulture);
            }
        }
        
        public static string Fahrenheit_UnitItem_Name {
            get {
                return ResourceManager.GetString("Fahrenheit_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Fahrenheit_Temperature_Description {
            get {
                return ResourceManager.GetString("Fahrenheit_Temperature_Description", resourceCulture);
            }
        }
        
        public static string Velocity_Name {
            get {
                return ResourceManager.GetString("Velocity_Name", resourceCulture);
            }
        }
        
        public static string Velocity_Description {
            get {
                return ResourceManager.GetString("Velocity_Description", resourceCulture);
            }
        }
        
        public static string MetersPerSecond_UnitItem_Name {
            get {
                return ResourceManager.GetString("MetersPerSecond_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string MetersPerSecond_Velocity_Description {
            get {
                return ResourceManager.GetString("MetersPerSecond_Velocity_Description", resourceCulture);
            }
        }
        
        public static string MetersPerSecond_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("MetersPerSecond_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string KilometersPerHour_UnitItem_Name {
            get {
                return ResourceManager.GetString("KilometersPerHour_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string KilometersPerHour_Velocity_Description {
            get {
                return ResourceManager.GetString("KilometersPerHour_Velocity_Description", resourceCulture);
            }
        }
        
        public static string KilometersPerHour_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("KilometersPerHour_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string MilesPerHour_UnitItem_Name {
            get {
                return ResourceManager.GetString("MilesPerHour_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string MilesPerHour_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("MilesPerHour_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string MilesPerHour_Velocity_Description {
            get {
                return ResourceManager.GetString("MilesPerHour_Velocity_Description", resourceCulture);
            }
        }
        
        public static string ChangeDoublePropertyCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeDoublePropertyCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ChangeDoublePropertyCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeDoublePropertyCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string ClosePageCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ClosePageCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ClosePageCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ClosePageCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string Meter_Distance_Description {
            get {
                return ResourceManager.GetString("Meter_Distance_Description", resourceCulture);
            }
        }
        
        public static string DialogButton_Yes {
            get {
                return ResourceManager.GetString("DialogButton_Yes", resourceCulture);
            }
        }
        
        public static string DialogButton_No {
            get {
                return ResourceManager.GetString("DialogButton_No", resourceCulture);
            }
        }
        
        public static string DialogButton_Save {
            get {
                return ResourceManager.GetString("DialogButton_Save", resourceCulture);
            }
        }
        
        public static string DialogButton_DontSave {
            get {
                return ResourceManager.GetString("DialogButton_DontSave", resourceCulture);
            }
        }
        
        public static string RestartApplicationCommand_Info_Name {
            get {
                return ResourceManager.GetString("RestartApplicationCommand_Info_Name", resourceCulture);
            }
        }
        
        public static string RestartApplicationCommand_Info_Description {
            get {
                return ResourceManager.GetString("RestartApplicationCommand_Info_Description", resourceCulture);
            }
        }
        
        public static string LanguageProperty_RestartDialog_Title {
            get {
                return ResourceManager.GetString("LanguageProperty_RestartDialog_Title", resourceCulture);
            }
        }
        
        public static string LanguageProperty_RestartDialog_Message {
            get {
                return ResourceManager.GetString("LanguageProperty_RestartDialog_Message", resourceCulture);
            }
        }
        
        public static string ChangeStringPropertyCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeStringPropertyCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ChangeStringPropertyCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeStringPropertyCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string ToolsMenu_Name {
            get {
                return ResourceManager.GetString("ToolsMenu_Name", resourceCulture);
            }
        }
        
        public static string ToolsMenu_Settings {
            get {
                return ResourceManager.GetString("ToolsMenu_Settings", resourceCulture);
            }
        }
        
        public static string ToolsMenu_Home {
            get {
                return ResourceManager.GetString("ToolsMenu_Home", resourceCulture);
            }
        }
        
        public static string ChangeThemeCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeThemeCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string ChangeThemeCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeThemeCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string Mah_UnitItem_Name {
            get {
                return ResourceManager.GetString("Mah_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Capacity_UnitItem_Description {
            get {
                return ResourceManager.GetString("Capacity_UnitItem_Description", resourceCulture);
            }
        }
        
        public static string Mah_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Mah_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string ChangeBoolPropertyCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeBoolPropertyCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ChangeBoolPropertyCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeBoolPropertyCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string MilliAmpere_UnitItem_Name {
            get {
                return ResourceManager.GetString("MilliAmpere_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string MilliAmpere_Amperage_Description {
            get {
                return ResourceManager.GetString("MilliAmpere_Amperage_Description", resourceCulture);
            }
        }
        
        public static string MilliAmpere_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("MilliAmpere_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Ampere_UnitItem_Name {
            get {
                return ResourceManager.GetString("Ampere_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Amperage_AmpereUnit_Description {
            get {
                return ResourceManager.GetString("Amperage_AmpereUnit_Description", resourceCulture);
            }
        }
        
        public static string Ampere_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Ampere_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Volt_UnitItem_Name {
            get {
                return ResourceManager.GetString("Volt_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Volt_Voltage_Description {
            get {
                return ResourceManager.GetString("Volt_Voltage_Description", resourceCulture);
            }
        }
        
        public static string Volt_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Volt_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string MilliVolt_UnitItem_Name {
            get {
                return ResourceManager.GetString("MilliVolt_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string MilliVolt_Voltage_Description {
            get {
                return ResourceManager.GetString("MilliVolt_Voltage_Description", resourceCulture);
            }
        }
        
        public static string MilliVolt_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("MilliVolt_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Voltage_Name {
            get {
                return ResourceManager.GetString("Voltage_Name", resourceCulture);
            }
        }
        
        public static string Voltage_Description {
            get {
                return ResourceManager.GetString("Voltage_Description", resourceCulture);
            }
        }
        
        public static string Amperage_Name {
            get {
                return ResourceManager.GetString("Amperage_Name", resourceCulture);
            }
        }
        
        public static string Amperage_Description {
            get {
                return ResourceManager.GetString("Amperage_Description", resourceCulture);
            }
        }
        
        public static string Progress_Name {
            get {
                return ResourceManager.GetString("Progress_Name", resourceCulture);
            }
        }
        
        public static string Progress_Description {
            get {
                return ResourceManager.GetString("Progress_Description", resourceCulture);
            }
        }
        
        public static string Percent_Progress_Description {
            get {
                return ResourceManager.GetString("Percent_Progress_Description", resourceCulture);
            }
        }
        
        public static string Mah_Capacity_Description {
            get {
                return ResourceManager.GetString("Mah_Capacity_Description", resourceCulture);
            }
        }
        
        public static string InParts_Progress_Description {
            get {
                return ResourceManager.GetString("InParts_Progress_Description", resourceCulture);
            }
        }
        
        public static string OpenSettingsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenSettingsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenSettingsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenSettingsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string OpenHomePageCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenHomePageCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenHomePageCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenHomePageCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string SettingsHotKeysListView_ResetButton_Content {
            get {
                return ResourceManager.GetString("SettingsHotKeysListView_ResetButton_Content", resourceCulture);
            }
        }
        
        public static string SettingsHotKeysListView_DataGrid_Command_Header {
            get {
                return ResourceManager.GetString("SettingsHotKeysListView_DataGrid_Command_Header", resourceCulture);
            }
        }
        
        public static string SettingsHotKeysListView_DataGrid_CustomHotKey_Header {
            get {
                return ResourceManager.GetString("SettingsHotKeysListView_DataGrid_CustomHotKey_Header", resourceCulture);
            }
        }
        
        public static string SettingsHotKeysListView_DataGrid_DefaultHotKey_Header {
            get {
                return ResourceManager.GetString("SettingsHotKeysListView_DataGrid_DefaultHotKey_Header", resourceCulture);
            }
        }
        
        public static string SettingsHotKeysListView_DataGrid_Description_Header {
            get {
                return ResourceManager.GetString("SettingsHotKeysListView_DataGrid_Description_Header", resourceCulture);
            }
        }
        
        public static string SettingsHotKeysListView_DataGrid_Source_Header {
            get {
                return ResourceManager.GetString("SettingsHotKeysListView_DataGrid_Source_Header", resourceCulture);
            }
        }
        
        public static string HotKeyViewModel_HotKeyCaptureDialog_Title {
            get {
                return ResourceManager.GetString("HotKeyViewModel_HotKeyCaptureDialog_Title", resourceCulture);
            }
        }
        
        public static string HotKeyViewModel_HotKeyCaptureDialog_Message {
            get {
                return ResourceManager.GetString("HotKeyViewModel_HotKeyCaptureDialog_Message", resourceCulture);
            }
        }
        
        public static string RttBox_NetworkError_ToolTip {
            get {
                return ResourceManager.GetString("RttBox_NetworkError_ToolTip", resourceCulture);
            }
        }
        
        public static string InParts_SDM_Description {
            get {
                return ResourceManager.GetString("InParts_SDM_Description", resourceCulture);
            }
        }
        
        public static string HomePageView_DeviceBrowser_Title {
            get {
                return ResourceManager.GetString("HomePageView_DeviceBrowser_Title", resourceCulture);
            }
        }
        
        public static string HomePageView_DeviceBrowser_NoneText {
            get {
                return ResourceManager.GetString("HomePageView_DeviceBrowser_NoneText", resourceCulture);
            }
        }
        
        public static string LogViewer_CommandInfo_Name {
            get {
                return ResourceManager.GetString("LogViewer_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string LogViewer_CommandInfo_Description {
            get {
                return ResourceManager.GetString("LogViewer_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string LogViewerView_LogMessagesList_Title {
            get {
                return ResourceManager.GetString("LogViewerView_LogMessagesList_Title", resourceCulture);
            }
        }
        
        public static string LogViewerView_LogMessagesList_TimeSection {
            get {
                return ResourceManager.GetString("LogViewerView_LogMessagesList_TimeSection", resourceCulture);
            }
        }
        
        public static string LogViewerView_LogMessagesList_CategorySection {
            get {
                return ResourceManager.GetString("LogViewerView_LogMessagesList_CategorySection", resourceCulture);
            }
        }
        
        public static string LogViewerView_LogMessagesList_MessageSection {
            get {
                return ResourceManager.GetString("LogViewerView_LogMessagesList_MessageSection", resourceCulture);
            }
        }
        
        public static string LogViewerViewModel_Title {
            get {
                return ResourceManager.GetString("LogViewerViewModel_Title", resourceCulture);
            }
        }
        
        public static string LogViewerViewModel_Pagination_SkippedFiltered {
            get {
                return ResourceManager.GetString("LogViewerViewModel_Pagination_SkippedFiltered", resourceCulture);
            }
        }
        
        public static string LogViewerViewModel_Pagination_SkippedFilteredBy {
            get {
                return ResourceManager.GetString("LogViewerViewModel_Pagination_SkippedFilteredBy", resourceCulture);
            }
        }
        
        public static string ShellView_UnsplitAllTabsButton_ToolTip {
            get {
                return ResourceManager.GetString("ShellView_UnsplitAllTabsButton_ToolTip", resourceCulture);
            }
        }
        
        public static string CancelCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("CancelCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string CancelCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("CancelCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string RefreshCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("RefreshCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string RefreshCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("RefreshCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string FocusSearchBoxCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("FocusSearchBoxCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string FocusSearchBoxCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("FocusSearchBoxCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string TextSearchCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("TextSearchCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string TextSearchCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("TextSearchCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string SearchBoxView_MainTextBox_Watermark {
            get {
                return ResourceManager.GetString("SearchBoxView_MainTextBox_Watermark", resourceCulture);
            }
        }
        
        public static string OpenLogViewerCommand_Action_Title {
            get {
                return ResourceManager.GetString("OpenLogViewerCommand_Action_Title", resourceCulture);
            }
        }
        
        public static string OpenLogViewerCommand_Action_Description {
            get {
                return ResourceManager.GetString("OpenLogViewerCommand_Action_Description", resourceCulture);
            }
        }
    }
}
