//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Avalonia.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string InstalledPluginsView_Search {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Search", resourceCulture);
            }
        }
        
        public static string ChangeLanguageCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeLanguageCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ChangeLanguageCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeLanguageCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Uninstalled {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Uninstalled", resourceCulture);
            }
        }
        
        public static string SettingsAppearanceView_AppLanguage_Title {
            get {
                return ResourceManager.GetString("SettingsAppearanceView_AppLanguage_Title", resourceCulture);
            }
        }
        
        public static string ThemeService_Dark {
            get {
                return ResourceManager.GetString("ThemeService_Dark", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_LoadingError {
            get {
                return ResourceManager.GetString("InstalledPluginsView_LoadingError", resourceCulture);
            }
        }
        
        public static string ThemeService_Light {
            get {
                return ResourceManager.GetString("ThemeService_Light", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Uninstall {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Uninstall", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_UninstalledMessageTitle {
            get {
                return ResourceManager.GetString("InstalledPluginsView_UninstalledMessageTitle", resourceCulture);
            }
        }
        
        public static string ThemeService_System {
            get {
                return ResourceManager.GetString("ThemeService_System", resourceCulture);
            }
        }
        
        public static string SettingsAppearanceView_AppTheme_Title {
            get {
                return ResourceManager.GetString("SettingsAppearanceView_AppTheme_Title", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_UninstalledMessage {
            get {
                return ResourceManager.GetString("InstalledPluginsView_UninstalledMessage", resourceCulture);
            }
        }
        
        public static string SettingsAppearanceView_HubHeader_CommonSettings {
            get {
                return ResourceManager.GetString("SettingsAppearanceView_HubHeader_CommonSettings", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_CancelUninstall {
            get {
                return ResourceManager.GetString("InstalledPluginsView_CancelUninstall", resourceCulture);
            }
        }
        
        public static string SettingsUnitsView_Header_Name {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Name", resourceCulture);
            }
        }
        
        public static string SettingsUnitsView_Header_Description {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Description", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Tab_Description {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_Description", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Tab_AdditionalInfo {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo", resourceCulture);
            }
        }
        
        public static string SettingsUnitsView_Header_Selected {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Selected", resourceCulture);
            }
        }
        
        public static string SettingsUnitsView_Header_Default {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Default", resourceCulture);
            }
        }
        
        public static string Distance_Name {
            get {
                return ResourceManager.GetString("Distance_Name", resourceCulture);
            }
        }
        
        public static string Distance_Description {
            get {
                return ResourceManager.GetString("Distance_Description", resourceCulture);
            }
        }
        
        public static string ChangeThemeCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeThemeCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string PluginsMarketView_ToggleSwitch_OnlyVerified {
            get {
                return ResourceManager.GetString("PluginsMarketView_ToggleSwitch_OnlyVerified", resourceCulture);
            }
        }
        
        public static string ChangeThemeCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeThemeCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string PluginsMarketView_InfoBar_IsVerified_Message {
            get {
                return ResourceManager.GetString("PluginsMarketView_InfoBar_IsVerified_Message", resourceCulture);
            }
        }
        
        public static string OpenDebugCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenDebugCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_SelectedPluginIsNull {
            get {
                return ResourceManager.GetString("InstalledPluginsView_SelectedPluginIsNull", resourceCulture);
            }
        }
        
        public static string OpenDebugCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenDebugCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string PluginInstallerViewModel_InstallDialog_Title {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallDialog_Title", resourceCulture);
            }
        }
        
        public static string UndoCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("UndoCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string UndoCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("UndoCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string SettingsKeyMapView_Header_Name {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Header_Name", resourceCulture);
            }
        }
        
        public static string SettingsKeyMapView_Header_Description {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Header_Description", resourceCulture);
            }
        }
        
        public static string SettingsKeyMapView_Header_DefaultHotKey {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Header_DefaultHotKey", resourceCulture);
            }
        }
        
        public static string HomePageViewModel_Title {
            get {
                return ResourceManager.GetString("HomePageViewModel_Title", resourceCulture);
            }
        }
        
        public static string SettingsPageViewModel_Title {
            get {
                return ResourceManager.GetString("SettingsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string SettingsAppearanceViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsAppearanceViewModel_Name", resourceCulture);
            }
        }
        
        public static string SettingsUnitsViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsUnitsViewModel_Name", resourceCulture);
            }
        }
        
        public static string SettingsKeymapViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsKeymapViewModel_Name", resourceCulture);
            }
        }
        
        public static string NauticalMile_UnitItem_Name {
            get {
                return ResourceManager.GetString("NauticalMile_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string NauticalMile_Distance_Description {
            get {
                return ResourceManager.GetString("NauticalMile_Distance_Description", resourceCulture);
            }
        }
        
        public static string ShellView_WindowControlButton_Close {
            get {
                return ResourceManager.GetString("ShellView_WindowControlButton_Close", resourceCulture);
            }
        }
        
        public static string PluginInstallerViewModel_InstallDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        public static string PluginInstallerViewModel_InstallDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string ShellView_Toolbar_File {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_File", resourceCulture);
            }
        }
        
        public static string ShellView_Toolbar_Edit {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_Edit", resourceCulture);
            }
        }
        
        public static string ShellView_Toolbar_View {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_View", resourceCulture);
            }
        }
        
        public static string ShellView_Toolbar_Help {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_Help", resourceCulture);
            }
        }
        
        public static string SettingsKeyMapView_Header_CustomHotKey {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Header_CustomHotKey", resourceCulture);
            }
        }
        
        public static string SettingsKeyMapView_Action_ResetCustomHotKeys {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Action_ResetCustomHotKeys", resourceCulture);
            }
        }
        
        public static string DocumentPageViewModel_Title {
            get {
                return ResourceManager.GetString("DocumentPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string MapExamplePageViewModel_Title {
            get {
                return ResourceManager.GetString("MapExamplePageViewModel_Title", resourceCulture);
            }
        }
        
        public static string ChangeCurrentUnitItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeCurrentUnitItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ChangeCurrentUnitItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeCurrentUnitItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string Altitude_Name {
            get {
                return ResourceManager.GetString("Altitude_Name", resourceCulture);
            }
        }
        
        public static string Altitude_Description {
            get {
                return ResourceManager.GetString("Altitude_Description", resourceCulture);
            }
        }
        
        public static string Meter_UnitItem_Name {
            get {
                return ResourceManager.GetString("Meter_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Meter_Altitude_Description {
            get {
                return ResourceManager.GetString("Meter_Altitude_Description", resourceCulture);
            }
        }
        
        public static string Meter_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Meter_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Feet_UnitItem_Name {
            get {
                return ResourceManager.GetString("Feet_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Feet_Altitude_Description {
            get {
                return ResourceManager.GetString("Feet_Altitude_Description", resourceCulture);
            }
        }
        
        public static string Feet_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Feet_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string AmplitudeModulation_Name {
            get {
                return ResourceManager.GetString("AmplitudeModulation_Name", resourceCulture);
            }
        }
        
        public static string AmplitudeModulation_Description {
            get {
                return ResourceManager.GetString("AmplitudeModulation_Description", resourceCulture);
            }
        }
        
        public static string InParts_AmplitudeModulation_Description {
            get {
                return ResourceManager.GetString("InParts_AmplitudeModulation_Description", resourceCulture);
            }
        }
        
        public static string Percent_AmplitudeModulation_Description {
            get {
                return ResourceManager.GetString("Percent_AmplitudeModulation_Description", resourceCulture);
            }
        }
        
        public static string Bearing_Name {
            get {
                return ResourceManager.GetString("Bearing_Name", resourceCulture);
            }
        }
        
        public static string Bearing_Description {
            get {
                return ResourceManager.GetString("Bearing_Description", resourceCulture);
            }
        }
        
        public static string Degree_UnitItem_Name {
            get {
                return ResourceManager.GetString("Degree_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Degree_Bearing_Description {
            get {
                return ResourceManager.GetString("Degree_Bearing_Description", resourceCulture);
            }
        }
        
        public static string DM_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("DM_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string DM_Bearing_Description {
            get {
                return ResourceManager.GetString("DM_Bearing_Description", resourceCulture);
            }
        }
        
        public static string DM_UnitItem_Name {
            get {
                return ResourceManager.GetString("DM_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string DdmGp_Name {
            get {
                return ResourceManager.GetString("DdmGp_Name", resourceCulture);
            }
        }
        
        public static string DdmGp_Description {
            get {
                return ResourceManager.GetString("DdmGp_Description", resourceCulture);
            }
        }
        
        public static string InParts_UnitItem_Name {
            get {
                return ResourceManager.GetString("InParts_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string InParts_DdmGp_Description {
            get {
                return ResourceManager.GetString("InParts_DdmGp_Description", resourceCulture);
            }
        }
        
        public static string Percent_UnitItem_Name {
            get {
                return ResourceManager.GetString("Percent_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Percent_DdmGp_Description {
            get {
                return ResourceManager.GetString("Percent_DdmGp_Description", resourceCulture);
            }
        }
        
        public static string Ddm_µA_Symbol {
            get {
                return ResourceManager.GetString("Ddm_µA_Symbol", resourceCulture);
            }
        }
        
        public static string MicroAmp_UnitItem_Name {
            get {
                return ResourceManager.GetString("MicroAmp_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string MicroAmp_DdmGp_Description {
            get {
                return ResourceManager.GetString("MicroAmp_DdmGp_Description", resourceCulture);
            }
        }
        
        public static string MicroAmpRu_UnitItem_Name {
            get {
                return ResourceManager.GetString("MicroAmpRu_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string MicroAmpRu_DdmGp_Description {
            get {
                return ResourceManager.GetString("MicroAmpRu_DdmGp_Description", resourceCulture);
            }
        }
        
        public static string DdmLlz_Name {
            get {
                return ResourceManager.GetString("DdmLlz_Name", resourceCulture);
            }
        }
        
        public static string DdmLlz_Description {
            get {
                return ResourceManager.GetString("DdmLlz_Description", resourceCulture);
            }
        }
        
        public static string InParts_DdmLlz_Description {
            get {
                return ResourceManager.GetString("InParts_DdmLlz_Description", resourceCulture);
            }
        }
        
        public static string Percent_DdmLlz_Description {
            get {
                return ResourceManager.GetString("Percent_DdmLlz_Description", resourceCulture);
            }
        }
        
        public static string MicroAmp_DdmLlz_Description {
            get {
                return ResourceManager.GetString("MicroAmp_DdmLlz_Description", resourceCulture);
            }
        }
        
        public static string MicroAmpRu_DdmLlz_Description {
            get {
                return ResourceManager.GetString("MicroAmpRu_DdmLlz_Description", resourceCulture);
            }
        }
        
        public static string Angle_Description {
            get {
                return ResourceManager.GetString("Angle_Description", resourceCulture);
            }
        }
        
        public static string Degree_Angle_Description {
            get {
                return ResourceManager.GetString("Degree_Angle_Description", resourceCulture);
            }
        }
        
        public static string Angle_Name {
            get {
                return ResourceManager.GetString("Angle_Name", resourceCulture);
            }
        }
        
        public static string Degree_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Degree_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Ms_UnitItem_Name {
            get {
                return ResourceManager.GetString("Ms_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Ms_Angle_Description {
            get {
                return ResourceManager.GetString("Ms_Angle_Description", resourceCulture);
            }
        }
        
        public static string Ms_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Ms_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Dms_UnitItem_Name {
            get {
                return ResourceManager.GetString("Dms_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Dms_Angle_Description {
            get {
                return ResourceManager.GetString("Dms_Angle_Description", resourceCulture);
            }
        }
        
        public static string Dms_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Dms_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string FieldStrength_Name {
            get {
                return ResourceManager.GetString("FieldStrength_Name", resourceCulture);
            }
        }
        
        public static string FieldStrength_Description {
            get {
                return ResourceManager.GetString("FieldStrength_Description", resourceCulture);
            }
        }
        
        public static string MicroVoltsPerMeter_UnitItem_Name {
            get {
                return ResourceManager.GetString("MicroVoltsPerMeter_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string MicroVoltsPerMeter_FieldStrength_Description {
            get {
                return ResourceManager.GetString("MicroVoltsPerMeter_FieldStrength_Description", resourceCulture);
            }
        }
        
        public static string FieldStrength_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("FieldStrength_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Power_Name {
            get {
                return ResourceManager.GetString("Power_Name", resourceCulture);
            }
        }
        
        public static string PluginInstallerViewModel_InstallPluginAsync_Success {
            get {
                return ResourceManager.GetString("PluginInstallerViewModel_InstallPluginAsync_Success", resourceCulture);
            }
        }
        
        public static string Power_Description {
            get {
                return ResourceManager.GetString("Power_Description", resourceCulture);
            }
        }
        
        public static string Dbm_UnitItem_Name {
            get {
                return ResourceManager.GetString("Dbm_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Dbm_Power_Description {
            get {
                return ResourceManager.GetString("Dbm_Power_Description", resourceCulture);
            }
        }
        
        public static string Dbm_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Dbm_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Frequency_Name {
            get {
                return ResourceManager.GetString("Frequency_Name", resourceCulture);
            }
        }
        
        public static string Frequency_Description {
            get {
                return ResourceManager.GetString("Frequency_Description", resourceCulture);
            }
        }
        
        public static string Hertz_UnitItem_Name {
            get {
                return ResourceManager.GetString("Hertz_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Hertz_Frequency_Description {
            get {
                return ResourceManager.GetString("Hertz_Frequency_Description", resourceCulture);
            }
        }
        
        public static string Hertz_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Hertz_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Gigahertz_UnitItem_Name {
            get {
                return ResourceManager.GetString("Gigahertz_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Gigahertz_Frequency_Description {
            get {
                return ResourceManager.GetString("Gigahertz_Frequency_Description", resourceCulture);
            }
        }
        
        public static string Gigahertz_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Gigahertz_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Kilohertz_UnitItem_Name {
            get {
                return ResourceManager.GetString("Kilohertz_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Kilohertz_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Kilohertz_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Kilohertz_Frequency_Description {
            get {
                return ResourceManager.GetString("Kilohertz_Frequency_Description", resourceCulture);
            }
        }
        
        public static string Megahertz_UnitItem_Name {
            get {
                return ResourceManager.GetString("Megahertz_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Megahertz_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Megahertz_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Megahertz_Frequency_Description {
            get {
                return ResourceManager.GetString("Megahertz_Frequency_Description", resourceCulture);
            }
        }
        
        public static string Latitude_Name {
            get {
                return ResourceManager.GetString("Latitude_Name", resourceCulture);
            }
        }
        
        public static string Latitude_Description {
            get {
                return ResourceManager.GetString("Latitude_Description", resourceCulture);
            }
        }
        
        public static string Degree_Latitude_Description {
            get {
                return ResourceManager.GetString("Degree_Latitude_Description", resourceCulture);
            }
        }
        
        public static string Dms_Latitude_Description {
            get {
                return ResourceManager.GetString("Dms_Latitude_Description", resourceCulture);
            }
        }
        
        public static string Longitude_Name {
            get {
                return ResourceManager.GetString("Longitude_Name", resourceCulture);
            }
        }
        
        public static string Longitude_Description {
            get {
                return ResourceManager.GetString("Longitude_Description", resourceCulture);
            }
        }
        
        public static string Degree_Longitude_Description {
            get {
                return ResourceManager.GetString("Degree_Longitude_Description", resourceCulture);
            }
        }
        
        public static string Dms_Longitude_Description {
            get {
                return ResourceManager.GetString("Dms_Longitude_Description", resourceCulture);
            }
        }
        
        public static string Phase_Name {
            get {
                return ResourceManager.GetString("Phase_Name", resourceCulture);
            }
        }
        
        public static string Phase_Description {
            get {
                return ResourceManager.GetString("Phase_Description", resourceCulture);
            }
        }
        
        public static string Degree_Phase_Description {
            get {
                return ResourceManager.GetString("Degree_Phase_Description", resourceCulture);
            }
        }
        
        public static string Radian_UnitItem_Name {
            get {
                return ResourceManager.GetString("Radian_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Radian_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Radian_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string Radian_Phase_Description {
            get {
                return ResourceManager.GetString("Radian_Phase_Description", resourceCulture);
            }
        }
        
        public static string Sdm_Name {
            get {
                return ResourceManager.GetString("Sdm_Name", resourceCulture);
            }
        }
        
        public static string Sdm_Description {
            get {
                return ResourceManager.GetString("Sdm_Description", resourceCulture);
            }
        }
        
        public static string Percent_Sdm_Description {
            get {
                return ResourceManager.GetString("Percent_Sdm_Description", resourceCulture);
            }
        }
        
        public static string Temperature_Name {
            get {
                return ResourceManager.GetString("Temperature_Name", resourceCulture);
            }
        }
        
        public static string Temperature_Description {
            get {
                return ResourceManager.GetString("Temperature_Description", resourceCulture);
            }
        }
        
        public static string Kelvin_UnitItem_Name {
            get {
                return ResourceManager.GetString("Kelvin_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Kelvin_Temperature_Description {
            get {
                return ResourceManager.GetString("Kelvin_Temperature_Description", resourceCulture);
            }
        }
        
        public static string Celsius_UnitItem_Name {
            get {
                return ResourceManager.GetString("Celsius_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Celsius_Temperature_Description {
            get {
                return ResourceManager.GetString("Celsius_Temperature_Description", resourceCulture);
            }
        }
        
        public static string Fahrenheit_UnitItem_Name {
            get {
                return ResourceManager.GetString("Fahrenheit_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string Fahrenheit_Temperature_Description {
            get {
                return ResourceManager.GetString("Fahrenheit_Temperature_Description", resourceCulture);
            }
        }
        
        public static string Velocity_Name {
            get {
                return ResourceManager.GetString("Velocity_Name", resourceCulture);
            }
        }
        
        public static string Velocity_Description {
            get {
                return ResourceManager.GetString("Velocity_Description", resourceCulture);
            }
        }
        
        public static string MetersPerSecond_UnitItem_Name {
            get {
                return ResourceManager.GetString("MetersPerSecond_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string MetersPerSecond_Velocity_Description {
            get {
                return ResourceManager.GetString("MetersPerSecond_Velocity_Description", resourceCulture);
            }
        }
        
        public static string MetersPerSecond_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("MetersPerSecond_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string KilometersPerHour_UnitItem_Name {
            get {
                return ResourceManager.GetString("KilometersPerHour_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string KilometersPerHour_Velocity_Description {
            get {
                return ResourceManager.GetString("KilometersPerHour_Velocity_Description", resourceCulture);
            }
        }
        
        public static string KilometersPerHour_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("KilometersPerHour_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string MilesPerHour_UnitItem_Name {
            get {
                return ResourceManager.GetString("MilesPerHour_UnitItem_Name", resourceCulture);
            }
        }
        
        public static string MilesPerHour_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("MilesPerHour_UnitItem_Symbol", resourceCulture);
            }
        }
        
        public static string MilesPerHour_Velocity_Description {
            get {
                return ResourceManager.GetString("MilesPerHour_Velocity_Description", resourceCulture);
            }
        }
        
        public static string ChangeDoublePropertyCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeDoublePropertyCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ChangeDoublePropertyCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeDoublePropertyCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string ClosePageCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ClosePageCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ClosePageCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ClosePageCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string Meter_Distance_Description {
            get {
                return ResourceManager.GetString("Meter_Distance_Description", resourceCulture);
            }
        }
        
        public static string DialogPageViewModel_Title {
            get {
                return ResourceManager.GetString("DialogPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string DialogButton_Yes {
            get {
                return ResourceManager.GetString("DialogButton_Yes", resourceCulture);
            }
        }
        
        public static string DialogButton_No {
            get {
                return ResourceManager.GetString("DialogButton_No", resourceCulture);
            }
        }
        
        public static string DialogButton_Save {
            get {
                return ResourceManager.GetString("DialogButton_Save", resourceCulture);
            }
        }
        
        public static string DialogButton_DontSave {
            get {
                return ResourceManager.GetString("DialogButton_DontSave", resourceCulture);
            }
        }
        
        public static string RestartApplicationCommand_Info_Name {
            get {
                return ResourceManager.GetString("RestartApplicationCommand_Info_Name", resourceCulture);
            }
        }
        
        public static string RestartApplicationCommand_Info_Description {
            get {
                return ResourceManager.GetString("RestartApplicationCommand_Info_Description", resourceCulture);
            }
        }
        
        public static string LanguageProperty_RestartDialog_Title {
            get {
                return ResourceManager.GetString("LanguageProperty_RestartDialog_Title", resourceCulture);
            }
        }
        
        public static string LanguageProperty_RestartDialog_Message {
            get {
                return ResourceManager.GetString("LanguageProperty_RestartDialog_Message", resourceCulture);
            }
        }
        
        public static string PluginsMarketView_Install {
            get {
                return ResourceManager.GetString("PluginsMarketView_Install", resourceCulture);
            }
        }
        
        public static string PluginsMarketView_SelectedPluginIsNull {
            get {
                return ResourceManager.GetString("PluginsMarketView_SelectedPluginIsNull", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Tab_AdditionalInfo_Dependencies {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo_Dependencies", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_AllVersions {
            get {
                return ResourceManager.GetString("InstalledPluginsView_AllVersions", resourceCulture);
            }
        }
        
        public static string PluginsMarketView_Cancel {
            get {
                return ResourceManager.GetString("PluginsMarketView_Cancel", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Tab_AdditionalInfo_Author {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo_Author", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Tab_AdditionalInfo_DownloadCount {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo_DownloadCount", resourceCulture);
            }
        }
        
        public static string InstalledPluginsView_Tab_AdditionalInfo_Tags {
            get {
                return ResourceManager.GetString("InstalledPluginsView_Tab_AdditionalInfo_Tags", resourceCulture);
            }
        }
        
        public static string SourceViewModel_SourceViewModel_NameIsRequired {
            get {
                return ResourceManager.GetString("SourceViewModel_SourceViewModel_NameIsRequired", resourceCulture);
            }
        }
        
        public static string SourceViewModel_SourceViewModel_SourceUriIsRequired {
            get {
                return ResourceManager.GetString("SourceViewModel_SourceViewModel_SourceUriIsRequired", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_PluginsSourcesViewModel_ErrorToUpdate {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_PluginsSourcesViewModel_ErrorToUpdate", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_PluginsSourcesViewModel_ErrorToRemove {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_PluginsSourcesViewModel_ErrorToRemove", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_AddImpl_Title {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_AddImpl_Title", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_AddImpl_Add {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_AddImpl_Add", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_AddImpl_Cancel {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_AddImpl_Cancel", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_EditImpl_Title {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_EditImpl_Title", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_EditImpl_Save {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_EditImpl_Save", resourceCulture);
            }
        }
        
        public static string PluginsSourcesViewModel_AddAction_Label {
            get {
                return ResourceManager.GetString("PluginsSourcesViewModel_AddAction_Label", resourceCulture);
            }
        }
        
        public static string SourcesView_Name {
            get {
                return ResourceManager.GetString("SourcesView_Name", resourceCulture);
            }
        }
        
        public static string SourcesView_URL {
            get {
                return ResourceManager.GetString("SourcesView_URL", resourceCulture);
            }
        }
        
        public static string SourcesView_Username {
            get {
                return ResourceManager.GetString("SourcesView_Username", resourceCulture);
            }
        }
        
        public static string SourcesView_Password {
            get {
                return ResourceManager.GetString("SourcesView_Password", resourceCulture);
            }
        }
        
        public static string AddSerialPortCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("AddSerialPortCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string AddSerialPortCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("AddSerialPortCommand_CommandInfo_Description", resourceCulture);
            }
        }
    }
}
