//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Avalonia.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that adds a serial port.
        /// </summary>
        public static string AddSerialPortCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("AddSerialPortCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add serial port.
        /// </summary>
        public static string AddSerialPortCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("AddSerialPortCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude unit.
        /// </summary>
        public static string Altitude_Description {
            get {
                return ResourceManager.GetString("Altitude_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string Altitude_Name {
            get {
                return ResourceManager.GetString("Altitude_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amlitude modulation unit.
        /// </summary>
        public static string AmplitudeModulation_Description {
            get {
                return ResourceManager.GetString("AmplitudeModulation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude modulation.
        /// </summary>
        public static string AmplitudeModulation_Name {
            get {
                return ResourceManager.GetString("AmplitudeModulation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree unit.
        /// </summary>
        public static string Angle_Description {
            get {
                return ResourceManager.GetString("Angle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string Angle_Name {
            get {
                return ResourceManager.GetString("Angle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing unit.
        /// </summary>
        public static string Bearing_Description {
            get {
                return ResourceManager.GetString("Bearing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing.
        /// </summary>
        public static string Bearing_Name {
            get {
                return ResourceManager.GetString("Bearing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature in celsius.
        /// </summary>
        public static string Celsius_Temperature_Description {
            get {
                return ResourceManager.GetString("Celsius_Temperature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        public static string Celsius_UnitItem_Name {
            get {
                return ResourceManager.GetString("Celsius_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change unit sub type of the unit.
        /// </summary>
        public static string ChangeCurrentUnitItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeCurrentUnitItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change current unit item.
        /// </summary>
        public static string ChangeCurrentUnitItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeCurrentUnitItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command changes the value of a property with the double type.
        /// </summary>
        public static string ChangeDoublePropertyCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeDoublePropertyCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change double property.
        /// </summary>
        public static string ChangeDoublePropertyCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeDoublePropertyCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change application&apos;s language.
        /// </summary>
        public static string ChangeLanguageCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeLanguageCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChangeLanguageCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeLanguageCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command changes the value of a property with the string type.
        /// </summary>
        public static string ChangeStringPropertyCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeStringPropertyCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change string property.
        /// </summary>
        public static string ChangeStringPropertyCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeStringPropertyCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change application&apos;s theme.
        /// </summary>
        public static string ChangeThemeCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeThemeCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change theme.
        /// </summary>
        public static string ChangeThemeCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeThemeCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command closes current page.
        /// </summary>
        public static string ClosePageCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ClosePageCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close page.
        /// </summary>
        public static string ClosePageCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ClosePageCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power in decibels to 1 milliwatt.
        /// </summary>
        public static string Dbm_Power_Description {
            get {
                return ResourceManager.GetString("Dbm_Power_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decibel to 1 milliwatt.
        /// </summary>
        public static string Dbm_UnitItem_Name {
            get {
                return ResourceManager.GetString("Dbm_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dBm.
        /// </summary>
        public static string Dbm_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Dbm_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to µA.
        /// </summary>
        public static string Ddm_µA_Symbol {
            get {
                return ResourceManager.GetString("Ddm_µA_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference depth of modulation measure units.
        /// </summary>
        public static string DdmGp_Description {
            get {
                return ResourceManager.GetString("DdmGp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM (Gp).
        /// </summary>
        public static string DdmGp_Name {
            get {
                return ResourceManager.GetString("DdmGp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference depth of modulation measure units.
        /// </summary>
        public static string DdmLlz_Description {
            get {
                return ResourceManager.GetString("DdmLlz_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM (Llz).
        /// </summary>
        public static string DdmLlz_Name {
            get {
                return ResourceManager.GetString("DdmLlz_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle in degrees.
        /// </summary>
        public static string Degree_Angle_Description {
            get {
                return ResourceManager.GetString("Degree_Angle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing in degrees.
        /// </summary>
        public static string Degree_Bearing_Description {
            get {
                return ResourceManager.GetString("Degree_Bearing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude in degrees.
        /// </summary>
        public static string Degree_Latitude_Description {
            get {
                return ResourceManager.GetString("Degree_Latitude_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude in degrees.
        /// </summary>
        public static string Degree_Longitude_Description {
            get {
                return ResourceManager.GetString("Degree_Longitude_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase in degrees.
        /// </summary>
        public static string Degree_Phase_Description {
            get {
                return ResourceManager.GetString("Degree_Phase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string Degree_UnitItem_Name {
            get {
                return ResourceManager.GetString("Degree_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [D]°.
        /// </summary>
        public static string Degree_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Degree_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save.
        /// </summary>
        public static string DialogButton_DontSave {
            get {
                return ResourceManager.GetString("DialogButton_DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DialogButton_No {
            get {
                return ResourceManager.GetString("DialogButton_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DialogButton_Save {
            get {
                return ResourceManager.GetString("DialogButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DialogButton_Yes {
            get {
                return ResourceManager.GetString("DialogButton_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance unit.
        /// </summary>
        public static string Distance_Description {
            get {
                return ResourceManager.GetString("Distance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance_Name {
            get {
                return ResourceManager.GetString("Distance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing in degrees and minutes.
        /// </summary>
        public static string DM_Bearing_Description {
            get {
                return ResourceManager.GetString("DM_Bearing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees and minutes.
        /// </summary>
        public static string DM_UnitItem_Name {
            get {
                return ResourceManager.GetString("DM_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [D]°[M]&apos;.
        /// </summary>
        public static string DM_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("DM_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle in degrees, minutes and seconds.
        /// </summary>
        public static string Dms_Angle_Description {
            get {
                return ResourceManager.GetString("Dms_Angle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude in degrees, minutes and seconds.
        /// </summary>
        public static string Dms_Latitude_Description {
            get {
                return ResourceManager.GetString("Dms_Latitude_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude in degrees, minutes and seconds.
        /// </summary>
        public static string Dms_Longitude_Description {
            get {
                return ResourceManager.GetString("Dms_Longitude_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees, minutes and seconds.
        /// </summary>
        public static string Dms_UnitItem_Name {
            get {
                return ResourceManager.GetString("Dms_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D]°[M]′[S]′′.
        /// </summary>
        public static string Dms_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Dms_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature in fahrenheit.
        /// </summary>
        public static string Fahrenheit_Temperature_Description {
            get {
                return ResourceManager.GetString("Fahrenheit_Temperature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string Fahrenheit_UnitItem_Name {
            get {
                return ResourceManager.GetString("Fahrenheit_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude in feet.
        /// </summary>
        public static string Feet_Altitude_Description {
            get {
                return ResourceManager.GetString("Feet_Altitude_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string Feet_UnitItem_Name {
            get {
                return ResourceManager.GetString("Feet_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        public static string Feet_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Feet_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field strength unit.
        /// </summary>
        public static string FieldStrength_Description {
            get {
                return ResourceManager.GetString("FieldStrength_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field strength.
        /// </summary>
        public static string FieldStrength_Name {
            get {
                return ResourceManager.GetString("FieldStrength_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to µV/m.
        /// </summary>
        public static string FieldStrength_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("FieldStrength_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency unit.
        /// </summary>
        public static string Frequency_Description {
            get {
                return ResourceManager.GetString("Frequency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency_Name {
            get {
                return ResourceManager.GetString("Frequency_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency in gigahertz.
        /// </summary>
        public static string Gigahertz_Frequency_Description {
            get {
                return ResourceManager.GetString("Gigahertz_Frequency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigahertz.
        /// </summary>
        public static string Gigahertz_UnitItem_Name {
            get {
                return ResourceManager.GetString("Gigahertz_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHz.
        /// </summary>
        public static string Gigahertz_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Gigahertz_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency in hertz.
        /// </summary>
        public static string Hertz_Frequency_Description {
            get {
                return ResourceManager.GetString("Hertz_Frequency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hertz.
        /// </summary>
        public static string Hertz_UnitItem_Name {
            get {
                return ResourceManager.GetString("Hertz_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hz.
        /// </summary>
        public static string Hertz_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Hertz_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePageViewModel_Title {
            get {
                return ResourceManager.GetString("HomePageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude modulation in parts.
        /// </summary>
        public static string InParts_AmplitudeModulation_Description {
            get {
                return ResourceManager.GetString("InParts_AmplitudeModulation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM (Gp) in parts.
        /// </summary>
        public static string InParts_DdmGp_Description {
            get {
                return ResourceManager.GetString("InParts_DdmGp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM (Llz) in parts.
        /// </summary>
        public static string InParts_DdmLlz_Description {
            get {
                return ResourceManager.GetString("InParts_DdmLlz_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In parts.
        /// </summary>
        public static string InParts_UnitItem_Name {
            get {
                return ResourceManager.GetString("InParts_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature in kelvin.
        /// </summary>
        public static string Kelvin_Temperature_Description {
            get {
                return ResourceManager.GetString("Kelvin_Temperature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        public static string Kelvin_UnitItem_Name {
            get {
                return ResourceManager.GetString("Kelvin_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency in kilohertz.
        /// </summary>
        public static string Kilohertz_Frequency_Description {
            get {
                return ResourceManager.GetString("Kilohertz_Frequency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilohertz.
        /// </summary>
        public static string Kilohertz_UnitItem_Name {
            get {
                return ResourceManager.GetString("Kilohertz_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kHz.
        /// </summary>
        public static string Kilohertz_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Kilohertz_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers per hour.
        /// </summary>
        public static string KilometersPerHour_UnitItem_Name {
            get {
                return ResourceManager.GetString("KilometersPerHour_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/h.
        /// </summary>
        public static string KilometersPerHour_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("KilometersPerHour_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity in kilometers per hour.
        /// </summary>
        public static string KilometersPerHour_Velocity_Description {
            get {
                return ResourceManager.GetString("KilometersPerHour_Velocity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the changes to take effect, you need to restart the application.
        /// </summary>
        public static string LanguageProperty_RestartDialog_Message {
            get {
                return ResourceManager.GetString("LanguageProperty_RestartDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restart now?.
        /// </summary>
        public static string LanguageProperty_RestartDialog_Title {
            get {
                return ResourceManager.GetString("LanguageProperty_RestartDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude unit.
        /// </summary>
        public static string Latitude_Description {
            get {
                return ResourceManager.GetString("Latitude_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude_Name {
            get {
                return ResourceManager.GetString("Latitude_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude unit.
        /// </summary>
        public static string Longitude_Description {
            get {
                return ResourceManager.GetString("Longitude_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude_Name {
            get {
                return ResourceManager.GetString("Longitude_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency in megahertz.
        /// </summary>
        public static string Megahertz_Frequency_Description {
            get {
                return ResourceManager.GetString("Megahertz_Frequency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megahertz.
        /// </summary>
        public static string Megahertz_UnitItem_Name {
            get {
                return ResourceManager.GetString("Megahertz_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MHz.
        /// </summary>
        public static string Megahertz_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Megahertz_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude in meters.
        /// </summary>
        public static string Meter_Altitude_Description {
            get {
                return ResourceManager.GetString("Meter_Altitude_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance in meters.
        /// </summary>
        public static string Meter_Distance_Description {
            get {
                return ResourceManager.GetString("Meter_Distance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        public static string Meter_UnitItem_Name {
            get {
                return ResourceManager.GetString("Meter_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Meter_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Meter_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters per second.
        /// </summary>
        public static string MetersPerSecond_UnitItem_Name {
            get {
                return ResourceManager.GetString("MetersPerSecond_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string MetersPerSecond_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("MetersPerSecond_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity in meters per second.
        /// </summary>
        public static string MetersPerSecond_Velocity_Description {
            get {
                return ResourceManager.GetString("MetersPerSecond_Velocity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM (Gp) in microamp.
        /// </summary>
        public static string MicroAmp_DdmGp_Description {
            get {
                return ResourceManager.GetString("MicroAmp_DdmGp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM (Llz) in microamp.
        /// </summary>
        public static string MicroAmp_DdmLlz_Description {
            get {
                return ResourceManager.GetString("MicroAmp_DdmLlz_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microamp.
        /// </summary>
        public static string MicroAmp_UnitItem_Name {
            get {
                return ResourceManager.GetString("MicroAmp_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM (Gp) in microamp (Rus).
        /// </summary>
        public static string MicroAmpRu_DdmGp_Description {
            get {
                return ResourceManager.GetString("MicroAmpRu_DdmGp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM (Llz) in microamp (Rus).
        /// </summary>
        public static string MicroAmpRu_DdmLlz_Description {
            get {
                return ResourceManager.GetString("MicroAmpRu_DdmLlz_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microamp (Rus).
        /// </summary>
        public static string MicroAmpRu_UnitItem_Name {
            get {
                return ResourceManager.GetString("MicroAmpRu_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field strength in microvolts per meter.
        /// </summary>
        public static string MicroVoltsPerMeter_FieldStrength_Description {
            get {
                return ResourceManager.GetString("MicroVoltsPerMeter_FieldStrength_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microvolts per meter.
        /// </summary>
        public static string MicroVoltsPerMeter_UnitItem_Name {
            get {
                return ResourceManager.GetString("MicroVoltsPerMeter_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles per hour.
        /// </summary>
        public static string MilesPerHour_UnitItem_Name {
            get {
                return ResourceManager.GetString("MilesPerHour_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi/h.
        /// </summary>
        public static string MilesPerHour_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("MilesPerHour_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity in miles per hour.
        /// </summary>
        public static string MilesPerHour_Velocity_Description {
            get {
                return ResourceManager.GetString("MilesPerHour_Velocity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle in minutes and seconds.
        /// </summary>
        public static string Ms_Angle_Description {
            get {
                return ResourceManager.GetString("Ms_Angle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes and seconds.
        /// </summary>
        public static string Ms_UnitItem_Name {
            get {
                return ResourceManager.GetString("Ms_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [M]′[S]′′.
        /// </summary>
        public static string Ms_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Ms_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance in nautical miles.
        /// </summary>
        public static string NauticalMile_Distance_Description {
            get {
                return ResourceManager.GetString("NauticalMile_Distance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Mile.
        /// </summary>
        public static string NauticalMile_UnitItem_Name {
            get {
                return ResourceManager.GetString("NauticalMile_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Debug Window.
        /// </summary>
        public static string OpenDebugCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenDebugCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Debug Window.
        /// </summary>
        public static string OpenDebugCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenDebugCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude modulation in percents.
        /// </summary>
        public static string Percent_AmplitudeModulation_Description {
            get {
                return ResourceManager.GetString("Percent_AmplitudeModulation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM (Gp) in percents.
        /// </summary>
        public static string Percent_DdmGp_Description {
            get {
                return ResourceManager.GetString("Percent_DdmGp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM (Llz) in percents.
        /// </summary>
        public static string Percent_DdmLlz_Description {
            get {
                return ResourceManager.GetString("Percent_DdmLlz_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDM in percents.
        /// </summary>
        public static string Percent_Sdm_Description {
            get {
                return ResourceManager.GetString("Percent_Sdm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Percents.
        /// </summary>
        public static string Percent_UnitItem_Name {
            get {
                return ResourceManager.GetString("Percent_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase unit.
        /// </summary>
        public static string Phase_Description {
            get {
                return ResourceManager.GetString("Phase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        public static string Phase_Name {
            get {
                return ResourceManager.GetString("Phase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power unit.
        /// </summary>
        public static string Power_Description {
            get {
                return ResourceManager.GetString("Power_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Power_Name {
            get {
                return ResourceManager.GetString("Power_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase in radian.
        /// </summary>
        public static string Radian_Phase_Description {
            get {
                return ResourceManager.GetString("Radian_Phase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radian.
        /// </summary>
        public static string Radian_UnitItem_Name {
            get {
                return ResourceManager.GetString("Radian_UnitItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rad.
        /// </summary>
        public static string Radian_UnitItem_Symbol {
            get {
                return ResourceManager.GetString("Radian_UnitItem_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo the last action.
        /// </summary>
        public static string RedoCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("RedoCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string RedoCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("RedoCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that restarts the application.
        /// </summary>
        public static string RestartApplicationCommand_Info_Description {
            get {
                return ResourceManager.GetString("RestartApplicationCommand_Info_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Application.
        /// </summary>
        public static string RestartApplicationCommand_Info_Name {
            get {
                return ResourceManager.GetString("RestartApplicationCommand_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum depth of modulation measure units.
        /// </summary>
        public static string Sdm_Description {
            get {
                return ResourceManager.GetString("Sdm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDM.
        /// </summary>
        public static string Sdm_Name {
            get {
                return ResourceManager.GetString("Sdm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application&apos;s language.
        /// </summary>
        public static string SettingsAppearanceView_AppLanguage_Title {
            get {
                return ResourceManager.GetString("SettingsAppearanceView_AppLanguage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application&apos;s theme.
        /// </summary>
        public static string SettingsAppearanceView_AppTheme_Title {
            get {
                return ResourceManager.GetString("SettingsAppearanceView_AppTheme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Settings.
        /// </summary>
        public static string SettingsAppearanceView_HubHeader_CommonSettings {
            get {
                return ResourceManager.GetString("SettingsAppearanceView_HubHeader_CommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string SettingsAppearanceViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsAppearanceViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all to default .
        /// </summary>
        public static string SettingsKeyMapView_Action_ResetCustomHotKeys {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Action_ResetCustomHotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom hotkey.
        /// </summary>
        public static string SettingsKeyMapView_Header_CustomHotKey {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Header_CustomHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default hotKey.
        /// </summary>
        public static string SettingsKeyMapView_Header_DefaultHotKey {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Header_DefaultHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SettingsKeyMapView_Header_Description {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SettingsKeyMapView_Header_Name {
            get {
                return ResourceManager.GetString("SettingsKeyMapView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string SettingsKeymapViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsKeymapViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageViewModel_Title {
            get {
                return ResourceManager.GetString("SettingsPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsUnitsView_Header_Default {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SettingsUnitsView_Header_Description {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SettingsUnitsView_Header_Name {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string SettingsUnitsView_Header_Selected {
            get {
                return ResourceManager.GetString("SettingsUnitsView_Header_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string SettingsUnitsViewModel_Name {
            get {
                return ResourceManager.GetString("SettingsUnitsViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ShellView_Toolbar_Edit {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ShellView_Toolbar_File {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ShellView_Toolbar_Help {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ShellView_Toolbar_View {
            get {
                return ResourceManager.GetString("ShellView_Toolbar_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ShellView_WindowControlButton_Close {
            get {
                return ResourceManager.GetString("ShellView_WindowControlButton_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string ShellView_WindowControlButton_Collapse {
            get {
                return ResourceManager.GetString("ShellView_WindowControlButton_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen.
        /// </summary>
        public static string ShellView_WindowControlButton_Maximize {
            get {
                return ResourceManager.GetString("ShellView_WindowControlButton_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window mode.
        /// </summary>
        public static string ShellView_WindowControlButton_Minimize {
            get {
                return ResourceManager.GetString("ShellView_WindowControlButton_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature unit.
        /// </summary>
        public static string Temperature_Description {
            get {
                return ResourceManager.GetString("Temperature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature_Name {
            get {
                return ResourceManager.GetString("Temperature_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeService_Dark {
            get {
                return ResourceManager.GetString("ThemeService_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeService_Light {
            get {
                return ResourceManager.GetString("ThemeService_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string ThemeService_System {
            get {
                return ResourceManager.GetString("ThemeService_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolsMenu_Name {
            get {
                return ResourceManager.GetString("ToolsMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ToolsMenu_Settings {
            get {
                return ResourceManager.GetString("ToolsMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo the last action.
        /// </summary>
        public static string UndoCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("UndoCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UndoCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("UndoCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity unit.
        /// </summary>
        public static string Velocity_Description {
            get {
                return ResourceManager.GetString("Velocity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string Velocity_Name {
            get {
                return ResourceManager.GetString("Velocity_Name", resourceCulture);
            }
        }
    }
}
