//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.IO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Avalonia.IO.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} with address {1}.
        /// </summary>
        public static string HomePageDeviceItem_Description {
            get {
                return ResourceManager.GetString("HomePageDeviceItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaticId.
        /// </summary>
        public static string HomePageDeviceItem_Info_Id {
            get {
                return ResourceManager.GetString("HomePageDeviceItem_Info_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string HomePageDeviceItem_Info_Link {
            get {
                return ResourceManager.GetString("HomePageDeviceItem_Info_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string HomePageDeviceItem_Info_Type {
            get {
                return ResourceManager.GetString("HomePageDeviceItem_Info_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command to add/remove/change port.
        /// </summary>
        public static string PortCrudCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("PortCrudCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove/Change port.
        /// </summary>
        public static string PortCrudCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("PortCrudCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PortView_ButtonContent_Cancel {
            get {
                return ResourceManager.GetString("PortView_ButtonContent_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PortView_ButtonContent_Save {
            get {
                return ResourceManager.GetString("PortView_ButtonContent_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string PortView_Switch_Off {
            get {
                return ResourceManager.GetString("PortView_Switch_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string PortView_Switch_On {
            get {
                return ResourceManager.GetString("PortView_Switch_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Settings.
        /// </summary>
        public static string PortView_Title {
            get {
                return ResourceManager.GetString("PortView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate.
        /// </summary>
        public static string SerialPortView_Text_BaudRate {
            get {
                return ResourceManager.GetString("SerialPortView_Text_BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string SerialPortView_Text_Name {
            get {
                return ResourceManager.GetString("SerialPortView_Text_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string SerialPortView_TextPortName {
            get {
                return ResourceManager.GetString("SerialPortView_TextPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERIAL.
        /// </summary>
        public static string SerialPortViewModel_TagViewModel_Value {
            get {
                return ResourceManager.GetString("SerialPortViewModel_TagViewModel_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Serial port.
        /// </summary>
        public static string SettingsConnectionSerialExtension_MenuItem_Header {
            get {
                return ResourceManager.GetString("SettingsConnectionSerialExtension_MenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TCP port.
        /// </summary>
        public static string SettingsConnectionTcpExtension_MenuItem_Header {
            get {
                return ResourceManager.GetString("SettingsConnectionTcpExtension_MenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string SettingsPageExtension_TreePage_Title {
            get {
                return ResourceManager.GetString("SettingsPageExtension_TreePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string TcpPortView_Text_Host {
            get {
                return ResourceManager.GetString("TcpPortView_Text_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TcpPortView_Text_Name {
            get {
                return ResourceManager.GetString("TcpPortView_Text_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string TcpPortView_Text_PortNumber {
            get {
                return ResourceManager.GetString("TcpPortView_Text_PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP.
        /// </summary>
        public static string TcpPortViewModel_TagViewModel_Value {
            get {
                return ResourceManager.GetString("TcpPortViewModel_TagViewModel_Value", resourceCulture);
            }
        }
    }
}
