//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.IO {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Avalonia.IO.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SettingsConnectionTcpExtension_MenuItem_Header {
            get {
                return ResourceManager.GetString("SettingsConnectionTcpExtension_MenuItem_Header", resourceCulture);
            }
        }
        
        public static string PortView_Title {
            get {
                return ResourceManager.GetString("PortView_Title", resourceCulture);
            }
        }
        
        public static string SettingsPageExtension_TreePage_Title {
            get {
                return ResourceManager.GetString("SettingsPageExtension_TreePage_Title", resourceCulture);
            }
        }
        
        public static string TcpPortView_Text_PortNumber {
            get {
                return ResourceManager.GetString("TcpPortView_Text_PortNumber", resourceCulture);
            }
        }
        
        public static string TcpPortView_Text_Host {
            get {
                return ResourceManager.GetString("TcpPortView_Text_Host", resourceCulture);
            }
        }
        
        public static string TcpPortView_Text_Name {
            get {
                return ResourceManager.GetString("TcpPortView_Text_Name", resourceCulture);
            }
        }
        
        public static string PortView_ButtonContent_Save {
            get {
                return ResourceManager.GetString("PortView_ButtonContent_Save", resourceCulture);
            }
        }
        
        public static string PortView_ButtonContent_Cancel {
            get {
                return ResourceManager.GetString("PortView_ButtonContent_Cancel", resourceCulture);
            }
        }
        
        public static string SerialPortView_Text_Name {
            get {
                return ResourceManager.GetString("SerialPortView_Text_Name", resourceCulture);
            }
        }
        
        public static string SerialPortView_TextPortName {
            get {
                return ResourceManager.GetString("SerialPortView_TextPortName", resourceCulture);
            }
        }
        
        public static string SerialPortView_Text_BaudRate {
            get {
                return ResourceManager.GetString("SerialPortView_Text_BaudRate", resourceCulture);
            }
        }
        
        public static string PortView_Switch_On {
            get {
                return ResourceManager.GetString("PortView_Switch_On", resourceCulture);
            }
        }
        
        public static string PortView_Switch_Off {
            get {
                return ResourceManager.GetString("PortView_Switch_Off", resourceCulture);
            }
        }
        
        public static string SettingsConnectionSerialExtension_MenuItem_Header {
            get {
                return ResourceManager.GetString("SettingsConnectionSerialExtension_MenuItem_Header", resourceCulture);
            }
        }
        
        public static string TcpPortViewModel_TagViewModel_Value {
            get {
                return ResourceManager.GetString("TcpPortViewModel_TagViewModel_Value", resourceCulture);
            }
        }
        
        public static string SerialPortViewModel_TagViewModel_Value {
            get {
                return ResourceManager.GetString("SerialPortViewModel_TagViewModel_Value", resourceCulture);
            }
        }
        
        public static string PortCrudCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("PortCrudCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string PortCrudCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("PortCrudCommand_CommandInfo_Description", resourceCulture);
            }
        }
    }
}
