//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.Example {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Avalonia.Example.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DialogControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string MapControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("MapControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("HistoricalControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string ControlsGalleryPageViewModel_Title {
            get {
                return ResourceManager.GetString("ControlsGalleryPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string OpenControlsGalleryPageCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string OpenControlsGalleryPageCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_OpenFile_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_OpenFile_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_SaveFile_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SaveFile_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_SelectFolder_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SelectFolder_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_ObserveFolder_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ObserveFolder_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_YesOrNo_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_YesOrNo_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_YesOrNo_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_YesOrNo_Message", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_Save_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Save_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_Save_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Save_Message", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_HotKeyCapture_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_HotKeyCapture_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_HotKeyCapture_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_HotKeyCapture_Message", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_Input_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Input_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_Input_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Input_Message", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Note {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Note", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Description {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Description", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Description {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Custom_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Custom_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_System_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_Title", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_System_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_Description", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_LastResult {
            get {
                return ResourceManager.GetString("DialogControlsPageView_LastResult", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Rules_Description {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Rules_Description", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Rules_One {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Rules_One", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Rules_Many {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Rules_Many", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Common_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Common_Title", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Common_Message {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Common_Message", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Common_Severity {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Common_Severity", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Basic {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Basic", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_ActionButton {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_ActionButton", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Closable {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Closable", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_Examples {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Examples", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageView_ActionButton_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_ActionButton_Title", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_GeoPoint {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_GeoPoint", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Toggle {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Toggle", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_String {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_String", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Unit {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Unit", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Basic {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Basic", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Validation {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Validation", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageViewModel_Example_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageViewModel_Example_Title", resourceCulture);
            }
        }
        
        public static string InfoBoxControlsPageViewModel_Example_Message {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageViewModel_Example_Message", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_System_OpenFile {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_OpenFile", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_System_SaveFile {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_SaveFile", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_System_SelectFolder {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_SelectFolder", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_System_ObserveFolder {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_ObserveFolder", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Custom_YesOrNo {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_YesOrNo", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Custom_Save {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_Save", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Custom_Input {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_Input", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Custom_HotKeyCapture {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_HotKeyCapture", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_CancelResult {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_CancelResult", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_OpenFile_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_OpenFile_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_SaveFile_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SaveFile_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_SelectFolder_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SelectFolder_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_ObserveFolder_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ObserveFolder_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_YesOrNo_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_YesOrNo_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_Save_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Save_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_Input_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Input_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_HotKeyCapture_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_HotKeyCapture_Result", resourceCulture);
            }
        }
        
        public static string OpenControlsGalleryPageCommand_Action_Title {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_Action_Title", resourceCulture);
            }
        }
        
        public static string OpenControlsGalleryPageCommand_Action_Description {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_Action_Description", resourceCulture);
            }
        }
        
        public static string HistoricalControlsPageView_Enum {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Enum", resourceCulture);
            }
        }
        
        public static string DialogControlsPageViewModel_GeoPoint_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_GeoPoint_Result", resourceCulture);
            }
        }
        
        public static string DialogControlsPageView_Custom_GeoPoint {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_GeoPoint", resourceCulture);
            }
        }
    }
}
