//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.Example {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Avalonia.Example.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DialogPageViewModel_Title {
            get {
                return ResourceManager.GetString("DialogPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string MapExamplePageViewModel_Title {
            get {
                return ResourceManager.GetString("MapExamplePageViewModel_Title", resourceCulture);
            }
        }
        
        public static string DocumentPageViewModel_Title {
            get {
                return ResourceManager.GetString("DocumentPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string ParametersEditorParameterView_PinToggleButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_PinToggleButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorParameterView_UpdateButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_UpdateButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorParameterView_UpdateButton {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_UpdateButton", resourceCulture);
            }
        }
        
        public static string ParametersEditorParameterView_WriteButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_WriteButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorParameterView_WriteButton {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_WriteButton", resourceCulture);
            }
        }
        
        public static string ParametersEditorParameterView_RebootRequired {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_RebootRequired", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageView_StarsToggleButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_StarsToggleButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageView_UpdateButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_UpdateButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageView_PinsOffButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_PinsOffButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageViewModel_Search {
            get {
                return ResourceManager.GetString("ParametersEditorPageViewModel_Search", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageViewModel_Total {
            get {
                return ResourceManager.GetString("ParametersEditorPageViewModel_Total", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageView_StarButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_StarButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_Content {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_Content", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_Title {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_Title", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_CloseButtonText", resourceCulture);
            }
        }
        
        public static string MavParamsPageViewModel_DeviceName_Unknown {
            get {
                return ResourceManager.GetString("MavParamsPageViewModel_DeviceName_Unknown", resourceCulture);
            }
        }
    }
}
