//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Avalonia.Example {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Avalonia.Example.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls gallery.
        /// </summary>
        public static string ControlsGalleryPageViewModel_Title {
            get {
                return ResourceManager.GetString("ControlsGalleryPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common confirmations and inputs.
        /// </summary>
        public static string DialogControlsPageView_Custom_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open key capture dialog.
        /// </summary>
        public static string DialogControlsPageView_Custom_HotKeyCapture {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_HotKeyCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open input dialog.
        /// </summary>
        public static string DialogControlsPageView_Custom_Input {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open saving dialog.
        /// </summary>
        public static string DialogControlsPageView_Custom_Save {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom dialogs.
        /// </summary>
        public static string DialogControlsPageView_Custom_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open confirmation dialog.
        /// </summary>
        public static string DialogControlsPageView_Custom_YesOrNo {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Custom_YesOrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples of system and custom dialogs..
        /// </summary>
        public static string DialogControlsPageView_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last result.
        /// </summary>
        public static string DialogControlsPageView_LastResult {
            get {
                return ResourceManager.GetString("DialogControlsPageView_LastResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System dialogs are available on desktop platforms. Some options depend on OS capabilities..
        /// </summary>
        public static string DialogControlsPageView_Note {
            get {
                return ResourceManager.GetString("DialogControlsPageView_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File/folder pickers.
        /// </summary>
        public static string DialogControlsPageView_System_Description {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observe folder.
        /// </summary>
        public static string DialogControlsPageView_System_ObserveFolder {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_ObserveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string DialogControlsPageView_System_OpenFile {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string DialogControlsPageView_System_SaveFile {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string DialogControlsPageView_System_SelectFolder {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System dialogs.
        /// </summary>
        public static string DialogControlsPageView_System_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageView_System_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string DialogControlsPageViewModel_CancelResult {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_CancelResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the key.
        /// </summary>
        public static string DialogControlsPageViewModel_HotKeyCapture_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_HotKeyCapture_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotKey: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_HotKeyCapture_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_HotKeyCapture_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Capture.
        /// </summary>
        public static string DialogControlsPageViewModel_HotKeyCapture_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_HotKeyCapture_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass the data.
        /// </summary>
        public static string DialogControlsPageViewModel_Input_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Input_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_Input_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Input_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string DialogControlsPageViewModel_Input_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Input_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObserveFolder: opened {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_ObserveFolder_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ObserveFolder_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observe Folder.
        /// </summary>
        public static string DialogControlsPageViewModel_ObserveFolder_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_ObserveFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenFile: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_OpenFile_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_OpenFile_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string DialogControlsPageViewModel_OpenFile_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_OpenFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        public static string DialogControlsPageViewModel_Save_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Save_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveCancel: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_Save_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Save_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string DialogControlsPageViewModel_Save_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Save_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveFile: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_SaveFile_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SaveFile_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string DialogControlsPageViewModel_SaveFile_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SaveFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectFolder: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_SelectFolder_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SelectFolder_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string DialogControlsPageViewModel_SelectFolder_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_SelectFolder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs.
        /// </summary>
        public static string DialogControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit?.
        /// </summary>
        public static string DialogControlsPageViewModel_YesOrNo_Message {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_YesOrNo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YesNo: {0}.
        /// </summary>
        public static string DialogControlsPageViewModel_YesOrNo_Result {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_YesOrNo_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DialogControlsPageViewModel_YesOrNo_Title {
            get {
                return ResourceManager.GetString("DialogControlsPageViewModel_YesOrNo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string HistoricalControlsPageView_Basic {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples of historical properties with simple editing..
        /// </summary>
        public static string HistoricalControlsPageView_Description {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoPoint:.
        /// </summary>
        public static string HistoricalControlsPageView_GeoPoint {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_GeoPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules: non-empty; and second input additionally forbids ‘s’..
        /// </summary>
        public static string HistoricalControlsPageView_Rules_Description {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Rules_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many rules:.
        /// </summary>
        public static string HistoricalControlsPageView_Rules_Many {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Rules_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One rule:.
        /// </summary>
        public static string HistoricalControlsPageView_Rules_One {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Rules_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String (no validation):.
        /// </summary>
        public static string HistoricalControlsPageView_String {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle:.
        /// </summary>
        public static string HistoricalControlsPageView_Toggle {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        public static string HistoricalControlsPageView_Unit {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string HistoricalControlsPageView_Validation {
            get {
                return ResourceManager.GetString("HistoricalControlsPageView_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical fields.
        /// </summary>
        public static string HistoricalControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("HistoricalControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With action button.
        /// </summary>
        public static string InfoBoxControlsPageView_ActionButton {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_ActionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do action.
        /// </summary>
        public static string InfoBoxControlsPageView_ActionButton_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_ActionButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string InfoBoxControlsPageView_Basic {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closable.
        /// </summary>
        public static string InfoBoxControlsPageView_Closable {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Closable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string InfoBoxControlsPageView_Common_Message {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Common_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        public static string InfoBoxControlsPageView_Common_Severity {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Common_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string InfoBoxControlsPageView_Common_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Common_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline notification for app-wide messages. Examples below show basic usage, action button, and closable variants..
        /// </summary>
        public static string InfoBoxControlsPageView_Description {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string InfoBoxControlsPageView_Examples {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageView_Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example InfoBox message.
        /// </summary>
        public static string InfoBoxControlsPageViewModel_Example_Message {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageViewModel_Example_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example InfoBox title.
        /// </summary>
        public static string InfoBoxControlsPageViewModel_Example_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageViewModel_Example_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfoBox.
        /// </summary>
        public static string InfoBoxControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("InfoBoxControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Example.
        /// </summary>
        public static string MapControlsPageViewModel_Title {
            get {
                return ResourceManager.GetString("MapControlsPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open controls gallery.
        /// </summary>
        public static string OpenControlsGalleryPageCommand_Action_Description {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_Action_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls gallery.
        /// </summary>
        public static string OpenControlsGalleryPageCommand_Action_Title {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_Action_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that open&apos;s controls gallery.
        /// </summary>
        public static string OpenControlsGalleryPageCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open controls gallery.
        /// </summary>
        public static string OpenControlsGalleryPageCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenControlsGalleryPageCommand_CommandInfo_Name", resourceCulture);
            }
        }
    }
}
